# -*- coding: utf-8 -*-
"""Atividade dados nulos.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UZFN5Jke6gFgYLNMbsU7eBJ9Pk9TdpIm

# Importando as bibliotecas e plotando o gráfico original
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
!pip install seaborn==0.9.0
import numpy as np
import seaborn as sns
# %matplotlib inline
from matplotlib import pyplot as plt

"""**Gráfico sem valores nulos**"""

np.random.seed(6)
dados = pd.date_range('1/1/2017', periods=24, freq='M')
vendas = np.random.randint(low=20,high=25,size=24)
df = pd.DataFrame({'mes':dados, 'vendas':vendas})

sns.set_palette('Accent')
sns.set_style('darkgrid')
ax = sns.lineplot(x='mes', y='vendas', data=df)
ax.figure.set_size_inches(12,6)
ax.set_title('Vendas de sorteve por mês de 2017 até 2018', loc='left', fontsize=18)
ax.set_xlabel('Tempo', fontsize=14)
ax.set_ylabel('Vendas (R$)', fontsize=14)
plt.savefig('vendas_constantes.png')
ax = ax

"""# Removendo o valor da venda das vendas 23"""

df.loc[df.vendas == 23,['vendas']] = np.nan

df.head()

df['vendas'].isna().sum().sum()

"""**Ao tentar plotar, um erro será exibido informando que não temos tipos numéricos para agregar**"""

'''
sns.set_palette('Accent')
sns.set_style('darkgrid')
ax = sns.lineplot(x='mes', y='vendas', data=df)
ax.figure.set_size_inches(12,6)
ax.set_title('Vendas de sorteve por mês de 2017 até 2018', loc='left', fontsize=18)
ax.set_xlabel('Tempo', fontsize=14)
ax.set_ylabel('Vendas (R$)', fontsize=14)
plt.savefig('vendas_constantes.png')
ax = ax
'''

"""# Solução 1 - Preenchendo dados nulos com valor médio das vendas"""

df.fillna(df['vendas'].mean(),inplace=True)
df['vendas'] = df['vendas'].round()
df.tail(8)

sns.set_palette('Accent')
sns.set_style('darkgrid')
ax = sns.lineplot(x='mes', y='vendas', data=df)
ax.figure.set_size_inches(12,6)
ax.set_title('Vendas de sorteve por mês de 2017 até 2018', loc='left', fontsize=18)
ax.set_xlabel('Tempo', fontsize=14)
ax.set_ylabel('Vendas (R$)', fontsize=14)
plt.savefig('vendas_constantes.png')
ax = ax

"""# Solução 2 - Preenchendo com um valor específico"""

np.random.seed(6)
dados = pd.date_range('1/1/2017', periods=24, freq='M')
vendas = np.random.randint(low=20,high=25,size=24)
df = pd.DataFrame({'mes':dados, 'vendas':vendas})
df.loc[df.vendas == 23,['vendas']] = np.nan

df.isna().sum().sum()

"""**Preenchendo com o valor 21**"""

df.fillna(21,inplace=True)

df.isna().sum().sum()

sns.set_palette('Accent')
sns.set_style('darkgrid')
ax = sns.lineplot(x='mes', y='vendas', data=df)
ax.figure.set_size_inches(12,6)
ax.set_title('Vendas de sorteve por mês de 2017 até 2018', loc='left', fontsize=18)
ax.set_xlabel('Tempo', fontsize=14)
ax.set_ylabel('Vendas (R$)', fontsize=14)
plt.savefig('vendas_constantes.png')
ax = ax

"""# Solução 3 - Removendo dados nulos do DataFrame"""

df.isna().sum().sum()

df.dropna(inplace=True)

df.isna().sum().sum()

sns.set_palette('Accent')
sns.set_style('darkgrid')
ax = sns.lineplot(x='mes', y='vendas', data=df)
ax.figure.set_size_inches(12,6)
ax.set_title('Vendas de sorteve por mês de 2017 até 2018', loc='left', fontsize=18)
ax.set_xlabel('Tempo', fontsize=14)
ax.set_ylabel('Vendas (R$)', fontsize=14)
plt.savefig('vendas_constantes.png')
ax = ax

"""# Solução 4 - Preenchendo com o valor anterior ou posteior"""

np.random.seed(6)
dados = pd.date_range('1/1/2017', periods=24, freq='M')
vendas = np.random.randint(low=20,high=25,size=24)
df = pd.DataFrame({'mes':dados, 'vendas':vendas})
df.loc[df.vendas == 23,['vendas']] = np.nan

"""**ffill() - Anterior**"""

df.head()

df.ffill().head()

"""**bfill - posteior**"""

df.bfill().head()

"""# Solução 5 - Interpolando dados nulos com um com o valor médio"""

np.random.seed(6)
dados = pd.date_range('1/1/2017', periods=24, freq='M')
vendas = np.random.randint(low=20,high=25,size=24)
df = pd.DataFrame({'mes':dados, 'vendas':vendas})
df.loc[df.vendas == 23,['vendas']] = np.nan

df.head()

df.interpolate().head()

